# Generated by Django 5.1.4 on 2025-01-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountModel',
        ),
    ]
