# Generated by Django 5.1.4 on 2025-01-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='advertise_image/'),
        ),
    ]
