# Generated by Django 5.1.4 on 2025-01-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_alter_advertisemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='advertise/advertise_image/'),
        ),
    ]
