# Generated by Django 5.1.4 on 2025-02-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_alter_advertisemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisemodel',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
