# Generated by Django 5.1.4 on 2025-02-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0005_advertisemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisemodel',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
