# Generated by Django 5.1.4 on 2025-02-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0006_advertisemodel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisemodel',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='advertisemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
