# Generated by Django 5.1.4 on 2025-01-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_alter_advertisemodel_image'),
        ('rating_and_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingandreviewmodel',
            name='advertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='advertise.advertisemodel'),
        ),
    ]
