# Generated by Django 5.1.4 on 2025-01-09 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='advertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='advertise.advertisemodel'),
        ),
    ]
